### ISSUE TITLE
no watermark

### ISSUE THREAD

**Issue by thoriqazzikraa** [naseif/tiktok-scraper#12]
i think api2.musical.ly was down
so for no watermark error

**Comment by naseif** [comment]
I am looking into it. Thanks 🍺

**Comment by thoriqazzikraa** [comment]
> I am looking into it. Thanks 🍺

nice.
btw, you have instagram scraping?

**Comment by naseif** [comment]
@thoriqazzikraa Fixed in 6a8bea4a7f537d324610663aad90bff8e87bf2be, Please update the library to the latest version
