### ISSUE TITLE
fetchAllVideosFromUser giving invalid json response

### ISSUE THREAD

**Issue by lakshmins2021** [naseif/tiktok-scraper#15]
fetchAllVideosFromUser giving invalid json body response.A tiktok handle was given as input. Tried with and without @

**Comment by lakshmins2021** [comment]
caught err:  FetchError: invalid json response body at https://m.tiktok.com/api/post/item_list/?aid=1988&count=35&secUid=MS4wLjABAAAAQqjAgIjDmE8pFw6EMv2ouZN80n31txECe1vZfJ_4z9SEMpd1r2x0HQB2k9QYHHAK&cursor= reason: Unexpected end of JSON input

**Comment by naseif** [comment]
@lakshmins2021 Fixed in 6a8bea4a7f537d324610663aad90bff8e87bf2be, please update the library to the latest version
