### ISSUE TITLE
Feature : scrap hashtag posts

### ISSUE THREAD

**Issue by Spawnrad** [naseif/tiktok-scraper#3]
Hi,

Thank you a lot for this tiktok scraper working very well and very simple to use.

Is it possible to add the possibility to scrap hashtags ?

Thank you

**Comment by naseif** [comment]
> Hi,
> 
> Thank you a lot for this tiktok scraper working very well and very simple to use.
> 
> Is it possible to add the possibility to scrap hashtags ?
> 
> Thank you

I will be looking into this. Thanks for your feedback 👍🏻
