### ISSUE TITLE
Error video without watermark

### ISSUE THREAD

**Issue by theazran** [naseif/tiktok-scraper#9]
![image](https://user-images.githubusercontent.com/62879334/185025240-0df87c06-0f97-4db0-b0c1-a9e3895795a1.png)

**Comment by lizaemran** [comment]
Getting same error

**Comment by vanb** [comment]
I'm getting this error too. @naseif How was the current implementation discovered? I could try to dig in with any guidance.

**Comment by vanb** [comment]
I'm getting this error too. @naseif How was the current implementation discovered? I could try to dig in with any guidance.

It appears the fetchNoWaterInfo still returns a lot of data.
https://github.com/naseif/tiktok-scraper/blob/main/src/BL/Scrapers/TikTokScraper.ts#L405

But the download URL built with that data returns a 404 and the error message above.
https://github.com/naseif/tiktok-scraper/blob/main/src/BL/Scrapers/TikTokScraper.ts#L421

**Comment by naseif** [comment]
Looks like the api has changed. I will be looking into it. Thanks for the feedback.
@vanb I actually forgot where I discovered this method to get the video without watermark, but once I look into the data coming back from the API, I guess I will figure it out.

**Comment by naseif** [comment]
Please update the library to the latest version
